# Generated by Django 4.1.5 on 2023-02-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Transit', 'Transit')], default='Customer', max_length=20),
        ),
    ]
