# Generated by Django 4.1.5 on 2023-02-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='store.product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, to='store.order'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='store.product'),
        ),
    ]
