# Generated by Django 4.1.5 on 2023-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
    ]
