# Generated by Django 4.1.5 on 2023-02-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_profile_orders_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
    ]
