# Generated by Django 4.1.5 on 2023-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
