# Generated by Django 4.1.5 on 2023-02-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='product',
            name='nReviews',
            field=models.IntegerField(default=0),
        ),
    ]
