# Generated by Django 4.1.7 on 2023-02-28 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_profile_interest_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
