# Generated by Django 4.1.7 on 2023-02-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_remove_profile_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
