# Generated by Django 4.1.7 on 2023-02-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_message_time_alter_chatroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='id',
            new_name='room_name',
        ),
    ]
