# Generated by Django 4.1.5 on 2023-02-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='../static/defaultPic.png', upload_to=''),
        ),
    ]
