# Generated by Django 4.1.5 on 2023-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='../social/static/social/defaultPic.png', upload_to=''),
        ),
    ]
