# Generated by Django 4.1.5 on 2023-02-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_entry_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-dateTime']},
        ),
    ]
