# Generated by Django 4.1.5 on 2023-02-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_entry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='messaging',
            field=models.ManyToManyField(blank=True, to='social.profile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='profileOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='social.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='profileTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='social.profile'),
        ),
    ]
